name: Auto Commit

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update something.txt
        run: |
          RANDOM_WORDS=$(curl -s https://random-word-api.herokuapp.com/word?number=10 | jq -r '.[]' | paste -sd " " -)
          echo "$RANDOM_WORDS" > something.txt

      - name: Configure Git
        run: |
          git config --global user.name "akash-adhya"
          git config --global user.email "akashadhya19@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add something.txt
            git commit -m "Functional changes"
            git push
          else
            echo "No changes to commit or push."
          fi
